### PR TITLE
fix all_words_diff problem

### PR DESCRIPTION
**Pull request by matrix1001**
# What does this PR do?

fix terrible match algorithm in `all_words_diff`. See this for detail #451 .. some of the issue text is copied for easier reference

**Describe the bug**
image

**To Reproduce**
Run following command `textattack attack --model cnn-ag-news --recipe textbugger --num-examples 10`

**Expected behavior**
As shown in the pic, the real `Average perturbed word %` should not reach that high. I found the reason in `attack_recipes/shared/attacked_text.py:line 234`.

```python
    def all_words_diff(self, other_attacked_text):
        """Returns the set of indices for which this and other_attacked_text
        have different words."""
        indices = set()
        w1 = self.words
        w2 = other_attacked_text.words
        for i in range(min(len(w1), len(w2))):
            if w1[i] != w2[i]:
                indices.add(i)
        return indices
```

Apparently this comparison according to the absolute position is not proper. I believe we can find another proper algorithm.

after my fix, `Average perturbed word %` drop to about 20%, which it correct.

### CODE REVIEW

**Comment by qiyanjun** [comment]
@matrix1001 thanks for helping. please correct the pytest errors! and black format errors.

**Comment by jinyongyoo** [comment]
@matrix1001 Hi, can you provide an example where the previous implementation is incorrect and how your implementation fixes it?

**Comment by matrix1001** [comment]
@qiyanjun 

# example
raw: `aaa bbb ccc ddd`

changed: `a aa bbb ccc ddd`

old_result: all four words not match

my_result: only one word not match

# problem
I failed the test because I did not consider that some methods would delete words. Currently working on it.

**Comment by jxmorris12** [comment]
Hi @matrix1001 -- any update? Your word-matching algorithm is way better for the case you mentioned; we'd love to incorporate it if you can figure out how to include deleted words.

**Comment by matrix1001** [comment]
I have carefully thought about this. I believe that it's not cool to calculate perturbations after the attack. It's supposed to be calculate during the attack. My algorithm is still not good when encountering deleted words. Maybe I can find another proper algorithm.

**Comment by matrix1001** [comment]
@qiyanjun @jinyongyoo @jxmorris12 @heytitle 
I figure it out with ` Levenshtein distance` algorithm.

Code as follows:
```python
def generate_tokens(words):
    result = {}
    idx = 1
    for w in words:
        if w not in result:
            result[w] = idx
            idx += 1
    return result

def words_to_tokens(words, tokens):
    result = []
    for w in words:
        result.append(tokens[w])
    return result

def edit_distance(w1_t, w2_t):
    matrix = [[i + j for j in range(len(w2_t) + 1)] for i in range(len(w1_t) + 1)]

    for i in range(1, len(w1_t) + 1):
        for j in range(1, len(w2_t) + 1):
            if w1_t[i - 1] == w2_t[j - 1]:
                d = 0
            else:
                d = 1
            matrix[i][j] = min(matrix[i - 1][j] + 1, matrix[i][j - 1] + 1, matrix[i - 1][j - 1] + d)

    return matrix[len(w1_t)][len(w2_t)]


def cal_dif(w1, w2):
    tokens = generate_tokens(w1 + w2)
    w1_t = words_to_tokens(w1, tokens)
    w2_t = words_to_tokens(w2, tokens)
    return edit_distance(w1_t, w2_t)

print(cal_dif(['this', 'is', 'a', 'good', 'day'], ['this', 'a', 'good', 'day'])) #delete
print(cal_dif(['this', 'is', 'a', 'good', 'day'], ['this', 'is', 'aa', 'good', 'day'])) #change
print(cal_dif(['this', 'is', 'a', 'good', 'day'], ['this', 'is', 'a', 'real', 'good', 'day'])) #add
print(cal_dif(['this', 'is', 'a', 'good', 'day'], ['this', 'aa', 'real', 'good', 'day'])) #multiple
```

I am satisfied with the result. However, the algorithm only calculate mini changes. If the sentence is both deleted and added, the algorithm will consider only one change.

**Comment by matrix1001** [comment]
@qiyanjun @jinyongyoo @jxmorris12 @heytitle 
I figure it out with ` Levenshtein distance` algorithm.

Code as follows:
```python
def generate_tokens(words):
    result = {}
    idx = 1
    for w in words:
        if w not in result:
            result[w] = idx
            idx += 1
    return result

def words_to_tokens(words, tokens):
    result = []
    for w in words:
        result.append(tokens[w])
    return result

def edit_distance(w1_t, w2_t):
    matrix = [[i + j for j in range(len(w2_t) + 1)] for i in range(len(w1_t) + 1)]

    for i in range(1, len(w1_t) + 1):
        for j in range(1, len(w2_t) + 1):
            if w1_t[i - 1] == w2_t[j - 1]:
                d = 0
            else:
                d = 1
            matrix[i][j] = min(matrix[i - 1][j] + 1, matrix[i][j - 1] + 1, matrix[i - 1][j - 1] + d)

    return matrix[len(w1_t)][len(w2_t)]


def cal_dif(w1, w2):
    tokens = generate_tokens(w1 + w2)
    w1_t = words_to_tokens(w1, tokens)
    w2_t = words_to_tokens(w2, tokens)
    return edit_distance(w1_t, w2_t)

print(cal_dif(['this', 'is', 'a', 'good', 'day'], ['this', 'a', 'good', 'day'])) #delete
print(cal_dif(['this', 'is', 'a', 'good', 'day'], ['this', 'is', 'aa', 'good', 'day'])) #change
print(cal_dif(['this', 'is', 'a', 'good', 'day'], ['this', 'is', 'a', 'real', 'good', 'day'])) #add
print(cal_dif(['this', 'is', 'a', 'good', 'day'], ['this', 'aa', 'real', 'good', 'day'])) #multiple
```

I am satisfied with the result. However, the algorithm only calculate mini changes. If the sentence is both deleted and added, the algorithm will consider only one change.

**Comment by sanchit97** [comment]
@matrix1001 I think your commented algorithm works well. If you make a commit, we can go ahead and test it in Textattack.

**Comment by qiyanjun** [comment]
@sanchit97 can you fix the pytest errors? @matrix1001 please commit first.

**Comment by qiyanjun** [comment]
@matrix1001 please just run black to fix the format issue

**Review by jxmorris12 — APPROVED** [review]

**Comment by jxmorris12** [comment]
Please review and merge, @jinyongyoo!

**Review by qiyanjun — APPROVED** [review]

**Review by cogeid — APPROVED** [review]
These changes are good to go.

**Pull request merged**
