### PR TITLE
fix inflection generation and enlarge pos to upos mapping (for Morpheus)

### PR DESCRIPTION
**Pull request by a1noack**
I think `textattack/transformations/word_swap_inflections.py` had a couple issues. [These are issues in the sense that the Morpheus attack&ndash;that relies on this transformation&ndash;is not a correct copy of the authors' original implementation of Morpheus when it uses this transformation.]
Specifically:
**1.** The function `_get_replacement_words` wasn't returning the correct lists of inflections. For example, notice that
```
>>> lemminflect.getAllLemmas('is')
{'AUX': ('be',), 'VERB': ('be',)}
```

However, according to the Morpheus paper, we want not only 'be', but 'been', 'am', 'was', 'are', 'were', and 'being'. To get this full list, you must take one of the lemmas returned by `lemminflect.getAllLemmas` (in this case, 'be') and get its inflections: 

```
>>> lemminflect.getAllInflections('be', upos='VERB').values()
dict_values([('be',), ('was', 'were'), ('being',), ('been',), ('am', 'are'), ('is',)])
```
**2.** The number of considered POS tags was too low. The result was that many words that had inflections were being skipped over and not considered for replacement. Therefore, I expanded the mapping using the en-ptb (English Penn Treebank) POS to universal POS mapping introduced [here](https://github.com/slavpetrov/universal-pos-tags/blob/master/en-ptb.map).

### CODE REVIEW

**Review by jxmorris12 — APPROVED** [review]
Thanks for the detailed explanation, and commenting your code! This looks good to me!

**Comment by jxmorris12** [comment]
@a1noack run `make format` to format your code please. Then we can merge!

**Comment by a1noack** [comment]
Oops I had the wrong isort.

**Comment by jinyongyoo** [comment]
@a1noack  Thanks for fixing the issue!

**Pull request merged**
