### PR TITLE
Add chinese version of readme

### PR DESCRIPTION
**Pull request by Opdoop**
Thanks for releasing the powerful TextAttack🎉
For chinese fellows easier to get started with TextAttack, I translate the reademe to chinese. I try my best to adheres to `信、达、雅`,  the translation principles.  But only the content is guaranteed to be informative. This chinese version may need some major review. Despite all this, it's still a good startpoint.
Look forward to receiving your reply~

### CODE REVIEW

**Comment by qiyanjun** [comment]
@MintForever please help review this!

**Comment by Opdoop** [comment]
@qiyanjun Thanks for the reply~
And @MintForever, waiting for your constructive comment~

**Comment by qiyanjun** [comment]
@Opdoop can you help me also remove those HTML inline styles from the recipe table in the main Readme.md? 

BTW: please rebase! I did some other changes after your PR! https://textattack.readthedocs.io/en/latest/1start/support.html#start-contributing-pull-requests

**Comment by Opdoop** [comment]
Sorry, I'm a newbie at git. I'm not sure how to rebase after a PR. 😅
@qiyanjun I'll try it tomorrow.🧐

**Comment by Opdoop** [comment]
@qiyanjun Aloha~ I think I did it. 
And remove all in-line style and class="{odd}{even}" didn't change the appearance of the tables.

**Comment by Opdoop** [comment]
@MintForever Hi, I noticed the `review_readme_zh` branch, and thanks for your revision! ❤
Only a minor suggestion, the dash '——' in the HTML table title is used to fix the width of the column. Because the github preferred markdown wrap html table column by the max number of word of that column. Without this `——` some columns in the table were wrapped in an ugly way. Wish you figure out an elegant way. Or it's better to keep this dash.

**Comment by Opdoop** [comment]
One question: Where should the chinese version readme entry be placed?

**Comment by Opdoop** [comment]
Question: Where should the entry of chinese version readme be placed?

**Comment by qiyanjun** [comment]
@Opdoop have you solved @MintForever 's concern? 

@Opdoop I will add a link in the main READMe.md

**Comment by Opdoop** [comment]
@qiyanjun Hi, I did get it. @MintForever his review commits are on branch `review_readme_zh`, do you want me to merge his change in this PR?

**Comment by qiyanjun** [comment]
@Opdoop please merge @MintForever (her) change into the PR

**Comment by Opdoop** [comment]
@qiyanjun  Aha~Done~ Merged @MintForever (her) change into the PR 😃

**Comment by qiyanjun** [comment]
@Opdoop thanks. Last request of change: I have revised the ordering under the "Design" section. Can you revise your Chinese version accordingly? Many thanks,

**Comment by Opdoop** [comment]
@qiyanjun  Changed the order under the design section and added the Benchmarking section. 
I see you're trying to separate dataset and model into two sections. But  `HuggingFace support` and `Loading a model or dataset from a file` are still in a coupling.

**Comment by Opdoop** [comment]
I only modified `README_ZH.md`. I have no idea why the Test with PyTest failed.🤦‍♂️

**Comment by Opdoop** [comment]
The PyTest failing checks at install dependencies and the log is below:
```
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
Error: Process completed with exit code 2.
```
Still have no idea why this happened.

**Comment by qiyanjun** [comment]
@Opdoop Thanks.

**Review by qiyanjun — APPROVED** [review]

**Comment by Opdoop** [comment]
@qiyanjun Thank you for your valuable comments and suggestions.

**Pull request merged**
