### PR TITLE
fix issue 426 / where `DeletionAugmenter` deletes all the words in the text except one.

### LINKED ISSUE #426: The expected functionality of `DeletionAugmenter`
**Describe the bug**

Hi, I want to know the functionality of `DeletionAugmenter`. This augmenter returns only one word even though I set `pct_words_to_swap` to be 0.1.

**To Reproduce**
```python
from textattack.augmentation import DeletionAugmenter

augmenter = DeletionAugmenter(transformations_per_example=10, pct_words_to_swap=0.1)
s = "The United States and China may soon reach a trade agreement."
augmenter.augment(s)
```

```
['China.',
 'China.',
 'The.',
 'United.',
 'United.',
 'United.',
 'reach.',
 'reach.',
 'soon.',
 'trade.']
```

**Expected behavior**

**Screenshots or Traceback**
If applicable, add screenshots to help explain your problem. Also, copy and paste tracebacks produced by the bug. 

**System Information (please complete the following information):**
 - OS: MacOS
 - Library versions torch==1.6.0
 - Textattack version: 0.2.15

**Additional context**

### PR DESCRIPTION
**Pull request by cogeid**
# What does this PR do?

## Summary
This PR fixes #426, where `DeletionAugmenter` deletes all the words in the text except one.

Some description from the original PR: 
from: gpengzhi commented on Feb 25 • 

**Describe the bug**

Hi, I want to know the functionality of `DeletionAugmenter`. This augmenter returns only one word even though I set `pct_words_to_swap` to be 0.1.

**To Reproduce**
```python
from textattack.augmentation import DeletionAugmenter

augmenter = DeletionAugmenter(transformations_per_example=10, pct_words_to_swap=0.1)
s = "The United States and China may soon reach a trade agreement."
augmenter.augment(s)
```

```
['China.',
 'China.',
 'The.',
 'United.',
 'United.',
 'United.',
 'reach.',
 'reach.',
 'soon.',
 'trade.']
```

**Expected behavior**

**System Information (please complete the following information):**
 - OS: MacOS
 - Library versions torch==1.6.0
 - Textattack version: 0.2.15

**Additional context**
I'm having the same problem. 
I'm trying to augment some data with EDA where DelectionAugmenter class is also used. 
Some of the augmented lines that are returned contain only one word while the original consists of more than 20 words.
It seems that when returning the augmented data, the constrains are not applied and since the they are sorted before being returned, sometimes the one-word augmentations are the first to be selected.

## Changes
- Modified `utils.strings.words_from_text` to return [""] in case of deletion. Earlier it was returning an empty list which lead to `new_attack_attrs["modified_indices"]` never getting updated and we ended up deleting all the words except one.
```
# TODO implement w regex
if not s:
    return [""]  # for deletion
words = []
```
- Modified `AttackedText.generate_new_attacked_text` 
```
if adv_word_seq:  # adv_word_seq can be "" in case of deletion
    perturbed_text += original_text[:word_start]
```
```
if adv_word_seq:
    num_words_diff = adv_num_words - len(words_from_text(input_word))
else:
    num_words_diff = -1
```
```
# strip() to remove trailing space in case of deletion at the edge
perturbed_input_texts = perturbed_text.strip().split(AttackedText.SPLIT_TOKEN)
```

## Testing

```python
from textattack.augmentation import DeletionAugmenter

augmenter = DeletionAugmenter(transformations_per_example=10, pct_words_to_swap=0.1)
s = "The United States and China may soon reach a trade agreement."
augmenter.augment(s)
```

Output before the changes

```
['China.',
 'China.',
 'The.',
 'United.',
 'United.',
 'United.',
 'reach.',
 'reach.',
 'soon.',
 'trade.']
```

Output after the changes

```
['The States and China may soon reach a trade agreement.',
 'The United States China may soon reach a trade agreement.',
 'The United States and China may reach a trade agreement.',
 'The United States and China may soon a trade agreement.',
 'The United States and China may soon reach a agreement.',
 'The United States and China may soon reach a trade.',
 'The United States and China soon reach a trade agreement.',
 'The United States and may soon reach a trade agreement.',
 'The United and China may soon reach a trade agreement.',
 'United States and China may soon reach a trade agreement.']
```

## Checklist
- [ x ] The title of your pull request should be a summary of its contribution.
- [ x ] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [ x ] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the issue know you   are working on it)
- [ x ] To indicate a work in progress please mark it as a draft on Github.
- [ x ] Make sure existing tests pass.
- [ x ] Add relevant tests. No quality testing = no merge.
- [ x ] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify the appropriate `.rst` file in `TextAttack/docs/apidoc`.'

### CODE REVIEW

**Comment by qiyanjun** [comment]
@cogeid please don’t check into those result files...

**Comment by qiyanjun** [comment]
@cogeid I tried to reproduce: 

To Reproduce**
```python
from textattack.augmentation import DeletionAugmenter

augmenter = DeletionAugmenter(transformations_per_example=10, pct_words_to_swap=0.1)
s = "The United States and China may soon reach a trade agreement."
augmenter.augment(s)
```

However, the current master branch gives correct results..
```
['The States and China may soon reach a trade agreement.', 'The United States China may soon reach a trade agreement.', 'The United States and China may reach a trade agreement.', 'The United States and China may soon a trade agreement.', 'The United States and China may soon reach a agreement.', 'The United States and China may soon reach a trade.', 'The United States and China may soon reach trade agreement.', 'The United States and may soon reach a trade agreement.', 'The United and China may soon reach a trade agreement.', 'United States and China may soon reach a trade agreement.']
```

I don’t understand why we need to address this issue. It seems to have been solved in master.

**Comment by cogeid** [comment]
Hello Dr. Qi,

I just took another look at this issue, it seems to be not 100%
reproducible, but the bug still can occur. I think I will take look at this
PR, and how exactly this bug is occurring.

[image: Screen Shot 2021-07-23 at 9.46.35 PM.png]

Best,

Chengyuan

**Comment by qiyanjun** [comment]
This is a library dependency version issue... the current master plus --force-reinstall of all dependent library makes the bug disappear

**Pull request closed without merging**
