### PR TITLE
Sample notebook for explaining bert using captum WIP

### PR DESCRIPTION
**Pull request by sanchit97**
+ Added a notebook using textattack api and captum to explain simple BERT model
+ Added code for visualization 
+ [WIP] Correctness of visualization

### CODE REVIEW

**Comment by qiyanjun** [comment]
@sanchit97, please rebase

**Comment by qiyanjun** [comment]
@sanchit97 
509
Warning, treated as error:
510
/home/runner/work/TextAttack/TextAttack/docs/2notebook/Example_5_Explain_BERT.ipynb:6:Each notebook should have at least one section title

**Comment by sanchit97** [comment]
Added a section to the notebook because of failing tests

**Comment by qiyanjun** [comment]
@sanchit97 is this complete?

**Comment by sanchit97** [comment]
Yes, all the basic components are in place

**Comment by qiyanjun** [comment]
@sanchit97 I am combining this with some other document updates I am making.

**Pull request closed without merging**
