### PR TITLE
Added hard label attack goal function

### PR DESCRIPTION
**Pull request by ankitgv0**
# What does this PR do?
This PR adds a new Goal Function, called "HardLabelClassification", which finds the maximum semantic similarity between two pieces of text such that the generated text is outside of the target model's decision boundary.

## Summary
This PR adds the [Hard Label Classification](https://arxiv.org/pdf/2012.14956.pdf) goal function, which finds the maximum semantic similarity between two pieces of text such that the generated text is outside of the target model's decision boundary. Below is an example use case, where the user would be able to specify "goal-function hard-label-classification". The implementation for the goal function is based on the [paper](https://arxiv.org/pdf/2012.14956.pdf) as well as the corresponding [implementation](https://github.com/RishabhMaheshwary/hard-label-attack/blob/main/classification_attack.py), but only the goal function is being implemented as part of TextAttack.

hardlabeluse

## Additions
- Added a new Goal Function file in the classification folder called "hardlabel_classification.py"
- Specified the new objective function for the Goal Function in the file

## Changes
- The "hardlabel-classification" attack argument was created for hard label attacks.

## Deletions
- There were no deletions made for this PR.

## Checklist
- [x] The title of your pull request should be a summary of its contribution.
- [x] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [x] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the issue know you   are working on it)
- [x] To indicate a work in progress please mark it as a draft on Github.
- [  ] Make sure existing tests pass.
- [  ] Add relevant tests. No quality testing = no merge.
- [  ] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify the appropriate `.rst` file in `TextAttack/docs/apidoc`.'

### CODE REVIEW

**Comment by jxmorris12** [comment]
@ankitgv0 Let me know when this is ready to review!

**Comment by jxmorris12** [comment]
Why close this @cogeid?

**Comment by cogeid** [comment]
> Why close this @cogeid?

Hey jack I was trying to rerun the pytest for this PR by closing and reopening it (I now realize this was bad practice), but it seems like the repository that submitted this PR has been deleted? I will make a copy of this PR instead.

**Comment by qiyanjun** [comment]
@cogeid please reopen this PR!

**Pull request closed without merging**
