### PR TITLE
Change check_robustness dataset

### PR DESCRIPTION
**Pull request by Opdoop**
As Adversarial training using training data, although here has a random sample, it's more reasonable to use eval data to check robustness.

### CODE REVIEW

**Comment by qiyanjun** [comment]
@Opdoop let me check the doc error.

**Comment by qiyanjun** [comment]
@Opdoop please rebase

**Comment by Opdoop** [comment]
@qiyanjun Rebased

**Review by jxmorris12 — APPROVED** [review]
I think that evaluating adversarial robustness using the evaluation dataset is a reasonable default!

**Pull request merged**
