### PR TITLE
Proposed solution to Issue #447

### PR DESCRIPTION
**Pull request by Ashiq5**
# What does this PR do?

## Summary
*Example: This PR provides a solution to Issue #447*

### CODE REVIEW

**Comment by qiyanjun** [comment]
@Ashiq5 thanks for helping. Please run black to fix the formatting issues

**Comment by jxmorris12** [comment]
@Ashiq5 can you format and push your branch? It looks good to me, so we can approve and merge once you've done that! If you haven't yet, you can read more about our formatter/code styling tools in the [CONTRIBUTING.md doc](https://github.com/QData/TextAttack/blob/master/CONTRIBUTING.md).

**Comment by Ashiq5** [comment]
@jxmorris12, sure. Will correct the format and push the new code as soon as possible.

**Comment by Ashiq5** [comment]
I have fixed the formatting. Please let me know if anything else is required.

**Review by jxmorris12 — APPROVED** [review]

**Comment by jxmorris12** [comment]
Great work @Ashiq5 - thanks for contributing!

**Pull request merged**
