### PR TITLE
Attack via API

### PR DESCRIPTION
**Pull request by jinyongyoo**
# What does this PR do?

## Summary
Performing attacks using the TextAttack API is quite limiting compared to using the command line commands because the users have to write their own code to support logging, saving checkpoint, and parallel processing. This PR intends to introduce some new support for attacking using TextAttack's API so that what can be done in command line can also be done using the API. However, this version does break a lot of backward compatibilities. 

## Additions
- Added new dataclasses ``AttackArgs``, ``AugmenterArgs``, ``DatasetArgs``, ``ModelArgs`` that are intended to represent arguments for specific features of TextAttack. 
- Added new module named `textattack.Attacker`.``Attacker`` takes in ``Attack``, ``textattack.datasets.Dataset``, and ``AttackArgs`` objects to perform attacks on the datasets with the same features for logging and saving checkpoints as the command line version.
- Added ``textattack.datasets.Dataset`` class. This takes in a list (or list-like) of tuples of ``(input, output)`` format. It is intended to the be the most basic class that other dataset classes extend from. The idea is to require all "dataset" inputs to be of type ``textattack.datasets.Dataset``, so it's clear the users what they need to pass as a "dataset" (behavior, an arbitrary list counted as a "dataset" technically). 

## Changes
- Removed ``attack_dataset`` method from ``Attack`` class and removed all the generator-related functionalities. Generator design is neat, but is less readable and maintainable. The idea is to remove all dataset-level attack features from ``Attack`` class and make ``Attacker`` handle the dataset level attacks. ``Attack`` is solely responsible for attacking single examples.
- Updated ``textattack.datasets.HuggingFaceDatasets`` to allow users to pass in their own ``datasets.Dataset`` objects (instead of just taking in ``name``, ``subset``, and ``split`` to load the dataset).
- Updated modules in `textattack.commands` to work with the new APIs.

### CODE REVIEW

**Comment by jinyongyoo** [comment]
This currently only seems to work with python==3.7 (and not 3.8).

**Comment by Opdoop** [comment]
I didn't run the new API in the PR, just a quick look, it seems the parallel attack is still using `multiprocessing.Queue`. 
Using the previous implementation, when attack on entire dataset will occur `Fatal Python error: Segmentation fault`. 
`faulthandler` shows this `out_queue.get` line cause corruption.
https://github.com/QData/TextAttack/blob/994a56caf29c7e0162d8fa5ec5d58eab58d30daa/textattack/commands/attack/run_attack_parallel.py#L148
I thought maybe queue cause memory leak, but `mprof` shows there is only a small memory usage increase(below) before corruption. 
image

Do you have any idea what cause the `Fatal Python error: Segmentation fault` ？

**Comment by jinyongyoo** [comment]
@Opdoop Can you provide the full command to run to trigger that error? As well as your Python version? One thing I've been noticing is that behavior of multiprocessing differs between 3.7 and 3.8.

**Comment by Opdoop** [comment]
I write a little script to run in train split actually. The command below could reproduce the same error:
```
textattack attack --recipe textfooler --model cnn-imdb --num-examples -1 --parallel --disable-stdout
```
And my python version is Python 3.7.6

**Comment by jinyongyoo** [comment]
@Opdoop This might be case of "works on my machine ¯\\_(ツ)_/¯". I'm not seeing the seg fault. Could you maybe try this and share the output? https://blog.richard.do/2018/03/18/how-to-debug-segmentation-fault-in-python/

**Comment by Opdoop** [comment]
```
(textattack)  ab@localhost  ~/Github/TextAttack/textattack/attack_normal_model  python -X faulthandler attack_cnn_sst2_textfooler.py
Reusing dataset glue (/u01/ab/.cache/huggingface/datasets/glue/sst2/1.0.0/7c99657241149a24692c402a5c3f34d4c9f1df5ac2e4c3759fadea38f6cb29c4)
textattack: Loading datasets dataset glue, subset sst2, split train.
textattack: Logging to CSV at path /u01/ab/Github/TextAttack/outputs/attacks/cnn-glue-sst2-train-textfooler.csv.
textattack: Running on 4 GPUs
  0%|                                                                                                  | 0/67349 [00:00<?, ?it/s]textattack: Loading textattack model: WordCNNForClassification
textattack: Loading textattack model: WordCNNForClassification
textattack: Loading textattack model: WordCNNForClassification
textattack: Loading textattack model: WordCNNForClassification
Using /u01/ab/.cache/tfhub/ to cache modules.
Using /u01/ab/.cache/tfhub/ to cache modules.
Using /u01/ab/.cache/tfhub/ to cache modules.
Using /u01/ab/.cache/tfhub/ to cache modules.
textattack: Goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'> compatible with model WordCNNForClassification.
Recipe: textfooler
textattack: Goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'> compatible with model WordCNNForClassification.
Recipe: textfooler
textattack: Goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'> compatible with model WordCNNForClassification.
Recipe: textfooler
Attack(
  (search_method): GreedyWordSwapWIR(
    (wir_method):  delete
  )
  (goal_function):  UntargetedClassification
  (transformation):  WordSwapEmbedding(
    (max_candidates):  50
    (embedding):  WordEmbedding
  )
  (constraints): 
    (0): WordEmbeddingDistance(
        (embedding):  WordEmbedding
        (min_cos_sim):  0.5
        (cased):  False
        (include_unknown_words):  True
        (compare_against_original):  True
      )
    (1): PartOfSpeech(
        (tagger_type):  nltk
        (tagset):  universal
        (allow_verb_noun_swap):  True
        (compare_against_original):  True
      )
    (2): UniversalSentenceEncoder(
        (metric):  angular
        (threshold):  0.840845057
        (window_size):  15
        (skip_text_shorter_than_window):  True
        (compare_against_original):  False
      )
    (3): RepeatModification
    (4): StopwordModification
    (5): InputColumnModification(
        (matching_column_labels):  ['premise', 'hypothesis']
        (columns_to_ignore):  {'premise'}
      )
  (is_black_box):  True
) 

textattack: Goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'> compatible with model WordCNNForClassification.
Recipe: textfooler
[Succeeded / Failed / Total] 29359 / 2421 / 32790:  49%|█████████████████                  | 32790/67349 [12:41<13:22, 43.04it/s]Fatal Python error: Segmentation fault

Thread 0x00007ff300141700 (most recent call first):
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/connection.py", line 379 in _recv
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/connection.py", line 407 in _recv_bytes
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/connection.py", line 250 in recv
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/pool.py", line 470 in _handle_results
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 870 in run
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x00007ff2aad96700 (most recent call first):
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/pool.py", line 422 in _handle_tasks
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 870 in run
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x00007ff2a8595700 (most recent call first):
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/pool.py", line 413 in _handle_workers
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 870 in run
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x00007ff2a5d94700 (most recent call first):
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/connection.py", line 368 in _send
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/connection.py", line 404 in _send_bytes
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/connection.py", line 200 in send_bytes
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/queues.py", line 242 in _feed
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 870 in run
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x00007ff2a5593700 (most recent call first):
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 300 in wait
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 552 in wait
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/site-packages/tqdm/_monitor.py", line 69 in run
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/threading.py", line 890 in _bootstrap

Current thread 0x00007ff30b24e740 (most recent call first):
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 298 in rebuild_storage_filename
  File "/u01/ab/anaconda3/envs/textattack/lib/python3.7/multiprocessing/queues.py", line 113 in get
  File "/u01/ab/Github/TextAttack/textattack/commands/attack/run_attack_parallel.py", line 150 in run
  File "/u01/ab/Github/TextAttack/textattack/commands/attack/attack_command.py", line 47 in run
  File "attack_cnn_sst2_textfooler.py", line 25 in <module>
[1]    143390 segmentation fault (core dumped)  python -X faulthandler attack_cnn_sst2_textfooler.py
```
Above is the traceback. I didn't change any attack flow, just added some notes. So the line number may inconsistent with main branch version.

**Comment by jinyongyoo** [comment]
@Opdoop Are you sure you've install the `attack-api` branch? From the traceback I can see execution of `run_attack_parallel.py` file, but that code has been moved to `textattack/Attacker.py`.

**Comment by Opdoop** [comment]
I did not install `attack-api` branch. This `Segmentation fault` is the bug in `master` branch. I'll try `attack-api` branch later.

**Comment by jinyongyoo** [comment]
@Opdoop Ah okay seems like I got confused a bit. Yeah I'm not sure why that bug is happening. I'll run the attacks again and see if it happens for the full dataset.

**Comment by willyptrain** [comment]
### Notebook Examples that Pass vs. Fail - from latest commits
**Pass:**
- **Example 2:** Constraints
- **Example 4:** Tensorflow
- **Example 6:** AllenNLP
- **Example 7:** Multilingual
- **Example 8:** Attacking BERT models w/ CAptum



**Fail or Need Updating:**
- **Example 0**: End_To_End Tutorial
  - Issue with **peek-dataset** command: Missing args.model parameter
    - Possible Fix: Change parameter to dataset_by_model, include in parsed arguments
  - Issue with **eval** command: "PyTorch model must be torch.nn.Module, got type {type(model)}"
    - The model is expecting a torch.nn.Module, but instead the HuggingFaceModelWrapper is being passed
- **Example 1**: Introduction_and_Transformations
  - Issue with Attacking Custom Datasets, getting IndexOutOfBounds Error
- **Example 3:** Augmentation
- **Example 5:** Attacking Sklearn models - running out of RAM, try outside of Google Colab, if possible.
- **Example 9:** Keras example needs updating to be compatible with this branch

**Comment by cogeid** [comment]
Notebook Tutorial

- Tutorial 1: Introduction_and_Transformations
https://textattack.readthedocs.io/en/latest/2notebook/1_Introduction_and_Transformations.html

Since the structures of some files and classes were changed in this PR, the original Tutorial has to be modified in order to run properly.

**The file attack.py has been moved from textattack.shared folder to textattack folder, so the original notebook code**

`from textattack.shared import Attack` **has to be changed to** `from textattack import Attack`

**The following lines must be added so that new data classes are imported**

`from textattack import AttackArgs`
`from textattack.datasets import Dataset`
`from textattack import Attacker`

**Issue with "Bonus: Attacking Custom Samples"**
AttributeError: 'Dataset' object has no attribute 'output_scale_factor'
Dataset is lacking the output_scale_factor field

(Apparently this issue was fixed and merged after the meeting, I will be checking if the tutorial works after the fix)

**Comment by tahmid-kazi** [comment]
Notebook Tutorial (comments): 
Notebook 5: Training the sklearn models fills up the RAM on Google Colab, so that part of the notebook needs to be updated to reduce space complexity. Model training is successful, but unable to test the Attack aspect (last cell) of the notebooks due to failure of the previous step.
Notebook 9: Attacking Keras models
https://textattack.readthedocs.io/en/latest/2notebook/Example_6_Keras.html
An error in the notebook occurs when setting up the Attack on the Keras model. Specifically, the error stems from the line: 
````text_array = np.array([words2tokens(text_input) for text_input in text_input_list]) ````
where NameError: name 'words2tokens' is not defined
Model training is successful, but unable to test the Attack aspect (last 2 cells) of the notebooks due to failure of the previous step.

**Comment by qiyanjun** [comment]
### Notebook Examples that Pass vs. Fail - from latest commits
**Pass:**
- **Example 2:** Constraints
- **Example 4:** Tensorflow
- **Example 6:** AllenNLP
- **Example 7:** Multilingual
- **Example 8:** Attacking BERT models w/ CAptum



**Fail or Need Updating:**
- **Example 0**: End_To_End Tutorial ( @cogeid please fix this!!)
  - Issue with **peek-dataset** command: Missing args.model parameter
    - Possible Fix: Change parameter to dataset_by_model, include in parsed arguments
  - Issue with **eval** command: "PyTorch model must be torch.nn.Module, got type {type(model)}"
    - The model is expecting a torch.nn.Module, but instead the HuggingFaceModelWrapper is being passed
- **Example 1**: Introduction_and_Transformations ( @MintForever  please fix this!!)
  - Issue with Attacking Custom Datasets, getting IndexOutOfBounds Error
- **Example 3:** Augmentation ( @Hanyu-Liu-123   please fix this!!)
- **Example 5:** Attacking Sklearn models - running out of RAM, try outside of Google Colab, if possible. ( @tahmid-kazi     please fix this!!)
- **Example 9:** Keras example needs updating to be compatible with this branch ( @   please fix this!!)

**Comment by cogeid** [comment]
Fixes to Example 0: End_To_End Tutorial ( @cogeid please fix this!!)

**in dataset_args.py**
line 176

add an attribute to solve this issue

`model = None`

Note that this only a short term fix and still wouldn't achieve the desired functionality of automatically detecting a dataset when given a model

**in model_args.py**
line 258

change

`from textattack.commands.train_model.train_args_helpers`

to 

`from textattack.commands.training.train_args_helpers`

**Pull request closed without merging**
