### PR TITLE
Enhance augment function

### PR DESCRIPTION
**Pull request by Hanyu-Liu-123**
# What does this PR do?

## Summary
This PR introduces 2 new augmenter parameters, `high_yield` and `fast_augment`. The `high_yield` option was originally implemented in [pull request #507](https://github.com/QData/TextAttack/pull/507) that still requires additional implementation before merging.

When `high_yield` is set to `True`, every augmentation that fits the criteria of a successful transformation will be added to the final output. In most cases, the high-yield augmenter will generate far more augmentations than what users specify in `transformations_per_example`.

When `fast_augment` is set to `True`, the augmenter terminate and return `transformations_per_example` number of transformations when the number of successful augmentations reaches `transformations_per_example`. 

This improves the running time of the augmenter but may cause skewness in returned augmentations  (speed is improved via early stop). 

## Additions
- Added `high_yield` and `fast_augment` parameters in augmenter

## Changes
- Changed the augment function, augmenter parser, and augment_command

## Checklist
- * [x] The title of your pull request should be a summary of its contribution.
- * [x] Please write a detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [  ] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the issue know you   are working on it)
- * [x] To indicate a work in progress please mark it as a draft on Github.
- * [x] Make sure existing tests pass.
- [  ] Add relevant tests. No quality testing = no merge.
- [  ] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify the appropriate `.rst` file in `TextAttack/docs/apidoc`.'

### CODE REVIEW

**Comment by qiyanjun** [comment]
@Hanyu-Liu-123 please consider using or improve the newly added metric module  #514 to check the quality of the augmented samples...

**Comment by Hanyu-Liu-123** [comment]
Hi @alexander-zap , this pull request is a truncated version of https://gitlab.com/taforkacc/textattack. Because the original pull request requires extensive structure changes, we were unable to incorporate your full addition at this moment, but would definitely like to include the `high_yield` parameter in the augmenter.

At your convenience, could you review this pull request that adds the `high_yield` parameter to the `augment()` function? Thanks!

**Comment by qiyanjun** [comment]
@Hanyu-Liu-123 please check out https://github.com/QData/TextAttack/blob/master/textattack/attack_results/attack_result.py to figure out how to use metric module

**Comment by Hanyu-Liu-123** [comment]
@qiyanjun Added the docstrings! 

Here's an sample output when running in interactive mode:
```
>>> Enter a sentence to augment, "q" to quit, "c" to view/change arguments:

>>> I would love to go to Chile but the tickets are 500 dollars

Augmenting...

Augmentations:

I would love to go to Chile but the tickets are 212 dollars 

I would love to go to Chile but the tickets are 332 dollars 

I would love to go to Chile but the tickets are 772 dollars 

I would love to go to Chile but the tickets are 981 dollars 

I would love to go to Norway but the tickets are 500 dollars 


Average Original Perplexity Score: 109.42
Average Augment Perplexity Score: 140.97
Average Augment USE Score: 0.84
```

**Comment by Hanyu-Liu-123** [comment]
[Slides](https://docs.google.com/presentation/d/1c2DSRp28FotxG1fspu_JqzrXP86hisiPlRfERmiYmik/edit?usp=sharing) explaining the limitation of fast-augment

**Review by qiyanjun — APPROVED** [review]

**Comment by qiyanjun** [comment]
> [Slides](https://docs.google.com/presentation/d/1c2DSRp28FotxG1fspu_JqzrXP86hisiPlRfERmiYmik/edit?usp=sharing) explaining the limitation of fast-augment

F4B09038-97A5-4DC7-BE9F-1D0404276745

**Pull request merged**
