### PR TITLE
fix IndexError when use WordSwapQWERTY to augment data #712

### PR DESCRIPTION
**Pull request by zzk0**
# What does this PR do?

fix IndexError when use WordSwapQWERTY to augment data #712 

## Changes
- WordSwapQWERTY: fix bug when raodomly choose an empty list
- Add test

## Checklist
- [x] The title of your pull request should be a summary of its contribution.
- [x] Please write detailed description of what parts have been newly added and what parts have been modified. Please also explain why certain changes were made.
- [x] If your pull request addresses an issue, please mention the issue number in the pull request description to make sure they are linked (and people consulting the issue know you   are working on it)
- [x] To indicate a work in progress please mark it as a draft on Github.
- [x] Make sure existing tests pass.
- [x] Add relevant tests. No quality testing = no merge.
- [x] All public methods must have informative docstrings that work nicely with sphinx. For new modules/files, please add/modify the appropriate `.rst` file in `TextAttack/docs/apidoc`.'

### CODE REVIEW

**Review by jxmorris12 — APPROVED** [review]
LGTM - thanks for adding a test! We'll merge as long as the tests pass.

**Comment by zzk0** [comment]
@jxmorris12 format code and refine the tests

**Comment by jxmorris12** [comment]
remember to run `make format` before you push

**Comment by zzk0** [comment]
when I run `make format`, there are so many files to be formatted.

```
        modified:   tests/test_attacked_text.py
        modified:   tests/test_constraints/test_pretransformation_constraints.py
        modified:   tests/test_word_embedding.py
        modified:   textattack/attack.py
        modified:   textattack/attack_args.py
        modified:   textattack/attack_recipes/morpheus_tan_2020.py
        modified:   textattack/attack_recipes/seq2sick_cheng_2018_blackbox.py
        modified:   textattack/augment_args.py
        modified:   textattack/augmentation/recipes.py
        modified:   textattack/commands/augment_command.py
        modified:   textattack/constraints/grammaticality/cola.py
        modified:   textattack/constraints/grammaticality/language_models/google_language_model/alzantot_goog_lm.py
        modified:   textattack/constraints/grammaticality/part_of_speech.py
        modified:   textattack/constraints/overlap/max_words_perturbed.py
        modified:   textattack/constraints/semantics/sentence_encoders/thought_vector.py
        modified:   textattack/dataset_args.py
        modified:   textattack/datasets/helpers/ted_multi.py
        modified:   textattack/goal_functions/goal_function.py
        modified:   textattack/goal_functions/text/minimize_bleu.py
        modified:   textattack/goal_functions/text/non_overlapping_output.py
        modified:   textattack/loggers/weights_and_biases_logger.py
        modified:   textattack/metrics/attack_metrics/words_perturbed.py
        modified:   textattack/metrics/quality_metrics/perplexity.py
        modified:   textattack/model_args.py
        modified:   textattack/models/helpers/lstm_for_classification.py
        modified:   textattack/models/tokenizers/glove_tokenizer.py
        modified:   textattack/search_methods/greedy_word_swap_wir.py
        modified:   textattack/shared/attacked_text.py
        modified:   textattack/trainer.py
        modified:   textattack/training_args.py
        modified:   textattack/transformations/word_swaps/word_swap_masked_lm.py
```

Here's the output, but there are still some errors that I don't know how to handle. It seems like there might be a problem with docformatter.

```
(lightning) percent1@ubuntu:~/code/TextAttack$ make format
black .
All done! ✨ 🍰 ✨
239 files left unchanged.
isort --atomic tests textattack
/home/percent1/anaconda3/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
WARNING: Unable to parse file tests due to [Errno 21] Is a directory: '/home/percent1/code/TextAttack/tests'
WARNING: Unable to parse file textattack due to [Errno 21] Is a directory: '/home/percent1/code/TextAttack/textattack'
docformatter --in-place --recursive textattack tests
Traceback (most recent call last):
  File "/home/percent1/anaconda3/envs/lightning/bin/docformatter", line 8, in <module>
    sys.exit(main())
  File "/home/percent1/anaconda3/envs/lightning/lib/python3.10/site-packages/docformatter/__main__.py", line 71, in main
    return _main(
  File "/home/percent1/anaconda3/envs/lightning/lib/python3.10/site-packages/docformatter/__main__.py", line 61, in _main
    return formator.do_format_files()
  File "/home/percent1/anaconda3/envs/lightning/lib/python3.10/site-packages/docformatter/format.py", line 156, in do_format_files
    result = self._do_format_file(filename)
  File "/home/percent1/anaconda3/envs/lightning/lib/python3.10/site-packages/docformatter/format.py", line 189, in _do_format_file
    formatted_source = self._do_format_code(source)
  File "/home/percent1/anaconda3/envs/lightning/lib/python3.10/site-packages/docformatter/format.py", line 234, in _do_format_code
    code = self._format_code(source)
  File "/home/percent1/anaconda3/envs/lightning/lib/python3.10/site-packages/docformatter/format.py", line 299, in _format_code
    token_string = self._do_format_docstring(
  File "/home/percent1/anaconda3/envs/lightning/lib/python3.10/site-packages/docformatter/format.py", line 406, in _do_format_docstring
    description = _syntax.wrap_description(
  File "/home/percent1/anaconda3/envs/lightning/lib/python3.10/site-packages/docformatter/syntax.py", line 272, in wrap_description
    text = do_preserve_links(text, indentation, wrap_length)
  File "/home/percent1/anaconda3/envs/lightning/lib/python3.10/site-packages/docformatter/syntax.py", line 97, in do_preserve_links
    url = f"{indentation}" + url.strip().split(sep=" ")[1].strip()
IndexError: list index out of range
Makefile:4: recipe for target 'format' failed
make: *** [format] Error 1
```

**Comment by jxmorris12** [comment]
oh weird. @zzk0 can you update isort, etc. and see if that fixes? if not maybe I can format it for you?

**Pull request closed without merging**
