### PR TITLE
added table with attack recipes

### PR DESCRIPTION
**Pull request by tahmid-kazi**

### CODE REVIEW

**Review by jxmorris12 — APPROVED** [review]
This is a good improvement!

@jinyongyoo do you think we should remove the bullet-point list of attack recipes, and just keep the table instead? Or should we include both?

**Comment by jinyongyoo** [comment]
I think we can replace the bullet-point list with the table. But I'm not sure what the `Accessibility` column is about. It seems to be about the goal function we are maximizing, right? I'm not sure if that's particularly helpful, since all of them have the same value "score". Instead, I think we should try to put some other pieces of information, such as search method, blackbox vs whitebox, and maybe even transformation (though maybe that'll be confusing with the `Perturbation` column).

**Comment by qiyanjun** [comment]
@tahmid-kazi can you update the table wrt @jinyongyoo comments?

**Comment by qiyanjun** [comment]
I will merge this first, and we can add more columns later.

**Pull request merged**
