### PR TITLE
Lazy module loading and optional dependencies

### PR DESCRIPTION
**Pull request by jinyongyoo**
This PR adds lazy loading scheme for modules that are not regularily used by TextAttack (e.g. Tensorflow, stanza). New addition:

- LazyLoader class that handles lazy module loading. This is an adaptation from Tensorflow's LazyLoader https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/lazy_loader.py. (Pretty funny we use it to lazy load Tensorflow)
- Lazy load Tensorflow and Tensorflow-related modules. Also removed `tensorflow`, `tensorflow_text`, `tensorflow_hub`, and `tensorboardX` from `requirements.txt`. If user needs to use a module that requires the following packages, `LazyLoader` prints out error telling them that they need to pip install them.
- Lazy load logging packages like `visdom` and `wandb` which are not critical for TextAttack. 
- Lazy load `stanza` and `sentence_transformers`

### CODE REVIEW

**Review by jxmorris12 — APPROVED** [review]
LGTM! Two questions.

1. Do you think there is a way to avoid passing `globals()` to every `LazyLoader` call? One thing I was thinking of is using reflection to traverse the call stack and grab the globals from the caller, but that might be too fancy.

2. What's the point of having `name` and `local_name` in `LazyLoader`? So that you can rename something if you want to? Maybe there was an instance where these two behaved differently, but I didn't see it

**Comment by jinyongyoo** [comment]
@jxmorris12 To be honest, I just took the code from Tensorflow and knows it works haha. I'm not sure why we have `local_name` and `name`. Also, I'm not sure of an alternative way to get global symbol table. I think those are definitely good questions we can try to answer when we have time down the road.

**Comment by Opdoop** [comment]
Run test command `textattack attack --recipe textfooler --model bert-base` enconter `ModuleNotFoundError: Lazy module loader cannot find module named `tensorflow_hub`. This might be because TextAttack does not automatically install some optional dependencies. Please run `pip install tensorflow_hub` to install the package.`
After I run `pip install tensorflow_hub` twice and got:
```
Requirement already satisfied: tensorflow_hub in ./anaconda3/envs/textattack/lib/python3.6/site-packages (0.10.0)
Requirement already satisfied: protobuf>=3.8.0 in ./anaconda3/envs/textattack/lib/python3.6/site-packages (from tensorflow_hub) (3.14.0)
Requirement already satisfied: numpy>=1.12.0 in ./anaconda3/envs/textattack/lib/python3.6/site-packages (from tensorflow_hub) (1.18.5)
Requirement already satisfied: six>=1.9 in ./anaconda3/envs/textattack/lib/python3.6/site-packages (from protobuf>=3.8.0->tensorflow_hub) (1.15.0)
```
Then run `textattack attack --recipe textfooler --model bert-base` again
still got `ModuleNotFoundError: Lazy module loader cannot find module named `tensorflow_hub`. This might be because TextAttack does not automatically install some optional dependencies. Please run `pip install tensorflow_hub` to install the package.`

**Comment by jxmorris12** [comment]
@Opdoop was that in colab or some other jupyter notebook setting?

**Comment by Opdoop** [comment]
@jxmorris12 it was in a brand new conda env. As lazy dependency released to PIP few hours ago in https://github.com/QData/TextAttack/pull/342,  this problem didn't go away:
> ModuleNotFoundError: Lazy module loader cannot find module named `tensorflow_hub`. This might be because TextAttack does not automatically install some optional dependencies. Please run `pip install tensorflow_hub` to install the package. 

Reproducing it:
```
conda create -n textattack python=3.6
conda activate textattack
pip install textattack
textattack attack --recipe textfooler --model bert-base-uncased-mr --num-examples 100
pip install tensorflow_hub
textattack attack --recipe textfooler --model bert-base-uncased-mr --num-examples 100
```

**Comment by Opdoop** [comment]
pip freeze is below:
```
bert-score==0.3.6
bpemb==0.3.2
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
cycler==0.10.0
dataclasses==0.8
datasets==1.1.2
decorator==4.4.2
Deprecated==1.2.10
dill==0.3.3
docopt==0.6.2
editdistance==0.5.3
filelock==3.0.12
flair==0.6.1.post1
ftfy==5.8
future==0.18.2
gdown==3.12.2
gensim==3.8.3
hyperopt==0.2.5
idna==2.10
Janome==0.4.1
joblib==0.17.0
kiwisolver==1.3.1
konoha==4.6.2
langdetect==1.0.8
language-tool-python==2.4.6
lemminflect==0.2.1
lru-dict==1.1.6
lxml==4.6.1
matplotlib==3.3.3
more-itertools==8.6.0
mpld3==0.3
multiprocess==0.70.11.1
networkx==2.5
nltk==3.5
num2words==0.5.10
numpy==1.18.5
overrides==3.0.0
packaging==20.4
pandas==1.1.4
Pillow==8.0.1
protobuf==3.14.0
pyarrow==2.0.0
pyparsing==2.4.7
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2020.4
regex==2020.11.13
requests==2.25.0
sacremoses==0.0.43
scikit-learn==0.23.2
scipy==1.4.1
segtok==1.5.10
sentencepiece==0.1.94
six==1.15.0
smart-open==3.0.0
sqlitedict==1.7.0
tabulate==0.8.7
tensorflow-hub==0.10.0
terminaltables==3.1.0
textattack==0.2.14
threadpoolctl==2.1.0
tokenizers==0.8.1rc2
torch==1.7.0
tqdm==4.49.0
transformers==3.3.0
typing-extensions==3.7.4.3
urllib3==1.26.2
wcwidth==0.2.5
word2number==1.1
wrapt==1.12.1
xxhash==2.0.0
```

**Comment by jinyongyoo** [comment]
@Opdoop Hi I can answer questions about that. That is actually an intended behavior. We decided to remove some of our dependencies that we thought were not critical to TextAttack because installations were becoming quite heavy. Some of dependencies that were removed includes Tensorflow and its related packages (e.g. `tensorflow_hub`). That message is basically telling you that TextAttack didn't install tensorflow and a requirement, and its your responsibility to `pip install` it.

**Comment by Opdoop** [comment]
@jinyongyoo Thanks for the reply. The lazy module is brilliant👍. But the problem I ran into is this: 
1. Create a brand new env for textattack
2. Install textattack
3. run test `textattack attack --recipe textfooler --model bert-base-uncased-mr --num-examples 100`
4. Encounter lazy module : ModuleNotFoundError: Lazy module loader cannot find module named `tensorflow_hub`.
5. run `pip install tensorflow_hub`
6. run test `textattack attack --recipe textfooler --model bert-base-uncased-mr --num-examples 100` again
7. Still show lazy module : ModuleNotFoundError: Lazy module loader cannot find module named `tensorflow_hub`.

Above is the pip freeze log which shows tensorflow_hub was installed, but still encounter lazy module:  ModuleNotFoundError

**Comment by jinyongyoo** [comment]
@Opdoop I was able to reproduce the error. I believe the issue is with `tensorflow_hub`. When I installed `tensorflow_hub` without installing tensorflow, and then install `tensorflow_hub`, I get the following output:
```
>>> import tensorflow_hub


Failed to import tensorflow. Please note that tensorflow is not installed by default when you install tensorflow_hub. This is so that users can decide which tensorflow package to use. To use tensorflow_hub, please install a current version of tensorflow by following the instructions at https://tensorflow.org/install and https://tensorflow.org/hub/installation.


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/qdata/jy2ma/miniconda3/envs/test/lib/python3.8/site-packages/tensorflow_hub/__init__.py", line 85, in <module>
    _ensure_tf_install()
  File "/p/qdata/jy2ma/miniconda3/envs/test/lib/python3.8/site-packages/tensorflow_hub/__init__.py", line 49, in _ensure_tf_install
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
```

Now, this is still confusing for end users, so we'll try to come up with a better solution/error message.

**Comment by Opdoop** [comment]
@jinyongyoo Thansk! Is this mean that currently `pip install tensorflow` could solve this error?

**Comment by jinyongyoo** [comment]
It fixed the issue for me.

**Comment by Opdoop** [comment]
Yes. Manually install Lazy load related package solved the issue. Hoping next the elegant Lazy load could be using more smoothly~

**Pull request merged**
