### PR TITLE
Initial type hinting

### PR DESCRIPTION
**Pull request by arxk9**
Definitely some kinks I have to work out

### CODE REVIEW

**Comment by qiyanjun** [comment]
@arxk9 please run

1. "black textattack" to correct formatting issues first.

**Comment by qiyanjun** [comment]
@arxk9 what is the status of this?

**Comment by qiyanjun** [comment]
@arxk9  please rebase . Any update?

**Comment by jxmorris12** [comment]
@arxk9 I'm closing this since you haven't updated it in six months. Hopefully you can get back to it soon.

**Pull request closed without merging**
